name: GitHub Custom Actions
on: workflow_dispatch

jobs:
  checkout_git_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        #uses: actions/cehckout@v4
        run: git clone https://github.com/nxginx19/desktop-tutorial.git
      - name: Install Tree
        run: sudo apt install tree -y
      - name: Investiagte Repo
        run: | 
          pwd
          tree




