name: GitHub Actions On Push
on: push

jobs:
  on-push-job:
    runs-on: ubuntu-latest

    steps:
      - name: First Step
        run: |
          echo "This is a step within a jon within a workflow"
          ls -lart
          
