name: Deploying Multiple Runners
on: workflow_dispatch

jobs:
  clone-website-and-run-podman:
    runs-on: ubuntu-latest

    steps:
      - name: Git Clone Repo
        run: git clone https://github.com/nxginx19/my-parrot-website
      - name: Move Website Files
        run: sudo mv ./my-parrot-website/* /usr/share/nginx/html/
      - name: Check Website Files
        run: ls -lart /usr/share/nginx/html
      - name: Start And Enable Nginx Service
        run: |
          sudo systemctl enable nginx
          sudo systemctl start nginx
      - name: Check Nginx service
        run: sudo systemctl status nginx
      - name: Test Web Service
        #run: python3 -c "import requests; r=requests.get('http://localhost:8080');print(r.status.code)"
        run: curl localhost:80



